spring.application.name=prestamos-backend

# MongoDB - local sin autenticacion
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=prestamos_db

# Server
server.port=8080

# JWT
jwt.secret=clave-super-secreta-prestamos-sistema-recaudo-2024-seguridad
jwt.expiration=86400000

# Logging
logging.level.com.prestamos=DEBUG
logging.level.org.springframework.security=DEBUG
